### ISSUE TITLE
Create tables

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/monitorMTF#15]
### Capacity

- [x] [No electricity](https://mtf-monitoring-tables-proposal.netlify.app/#/no-electricity)
- [x] [Prevalence](https://mtf-monitoring-tables-proposal.netlify.app/#/prevalence-of-other-devices) and [details ](https://mtf-monitoring-tables-proposal.netlify.app/#/details-of-other-devices) of other devices for solar

### Availability

- [x] [Top-/bottom-coded, split by source by time period and with distribution of values](https://mtf-monitoring-tables-proposal.netlify.app/#/top-bottom-coded)
- [x] [Missing info](https://mtf-monitoring-tables-proposal.netlify.app/#/missing-info). NOTE: assume aggregated overall.

### Reliability

- [x] [DK frequency](https://mtf-monitoring-tables-proposal.netlify.app/#/dont-know-frequency). Keep pooled/aggregated.
- [x] [DK duration](https://mtf-monitoring-tables-proposal.netlify.app/#/dont-know-duration). Keep pooled/aggregated

### Affordability

- [x] [ Under-reporting of total expenditure](https://mtf-monitoring-tables-proposal.netlify.app/#/under-reporting-of-total-expenditure). Add column for 0 items consumed.

### Formality

- [x] Prevalence of other payee
- [x] Details of other payee

### Exposure

- [x] Prevalence of other stove
- [x] Details of other stove
- [x] Prevalence of other/NA fuel
- [x] Details of other fuel
- [x] Prevalence of other cooking location
- [x] Details of other cooking location
- [x] Prevalence of other exhaust system
- [x] Details of other exhaust system

**Comment by arthur-shaw** [comment]
Closed in 4169169
