### ISSUE TITLE
Revise

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/monitorMTF#5]
- [ ] #13
- [x] Show interviews recommended to reject
- [x] Save (revised) recommendations to a new folder
- [x] Prevent user from rejecting until save/approve interviews to reject

**Comment by arthur-shaw** [comment]
Closed in 6e3b47a61da7e0506192bd3c73c4b511ee69c028, ef96357163f17d936402fa33a69f4a7821996150, and f3bf060fd5d468ad1cce2b94d53ceb79f00f9167
